### PR TITLE
the death era button now toggles

### PR DESCRIPTION
**Pull request by MelvinShwuaner**

### CODE REVIEW

**Comment by MelvinShwuaner** [comment]
ngl i want to give the god of gods a weapon which summons creatures instead of the god of god's special ability summoning them but idk pixel art

**Comment by MasonScarbro** [comment]
> ngl i want to give the god of gods a weapon which summons creatures instead of the god of god's special ability summoning them but idk pixel art

I don't either shit is way harder than it looks, Its got like theories and methods to make certain things pop and stuff there are entire classes on it, its crazy.

**Comment by MasonScarbro** [comment]
Quick question, I noticed you deleted the godhunter walk animation WITH the scythe, the weapon never actually appeared in their hands correctly (i.e the asset was of its axis) when the weapon was a seperate sprite, which is why I merged the image and made the scythe sprite invisible. Is that fixed? and If so what did you do to fix it?

**Comment by MelvinShwuaner** [comment]
Yes it is fixed, I added a JSON to the godhunter's sprite folder which offsets their sprite, so now they will hold all weapons correctly but there shadow is now to their left a bit

**Comment by MasonScarbro** [comment]
> s

Yea that's what I did but I could never get the spacing quite right without the shadow being too off.

**Pull request merged**
