### PR TITLE
GodofGods -> God of fire! 

### PR DESCRIPTION
**Pull request by MelvinShwuaner**
the god of gods has been replaced with god of fire, who has his own custom abilities and weapon!

The god of fire is still the most powerfull god, and his era is the age of ash along with the earth god (the earth god's status is stronger however)

The Staff Of  Fire: the god of fire's weapon, which shoots the same projectiles as mage's, and has the chaos laser in it, which deals a huge amount of damage

the god of fire also can summon red tornado's which set things on fire, fire storm, clouds of ash, and can summon demons, fire skulls and mages. he also can explode fire from himself

he can also morph into a dragon when there are too many enemies near him and will morph back when there are no enemies near him

the god of fire deals alot of damage while also having weak armor and health

ive tried balancing him but hes too op, pls balance things out for me!

### CODE REVIEW

**Comment by MelvinShwuaner** [comment]
uhh i think i fixed the merge conflict

**Comment by MelvinShwuaner** [comment]
im gonna test if therer is no bug

**Comment by MelvinShwuaner** [comment]
fixed the merge conflict!

**Review by MasonScarbro — APPROVED** [review]
Yippee!

**Pull request merged**
