### PR TITLE
Update Traits.cs

### PR DESCRIPTION
**Pull request by MelvinShwuaner**
i made an error, summoned beings can still attack buildings in their summoner's kingdom,i fixed it in here

as for harmony, basically the function canAttackTarget tells a creature if it can attack something, i made a "prefix" which adds code at the start of the function, this prefix adds additional questions to make it so summoned beings dont cause inconvenience to their summoner and his comrades

the god of gods trait has a custom icon which i put in  
i also nerfed god of gods trait a bit and buffed summoned ones a little, and made god of god's abilities chances customizable

i also added an era status to the god of gods and his summoned minions, the era is age of hope

and i also made it so god of gods can teleport their minions back to them if their minions are too far away

### CODE REVIEW

**Review by MasonScarbro — APPROVED** [review]

**Comment by MelvinShwuaner** [comment]
okay well i changed the stats of the god of gods effect and i also added a button to toggle if killing a god should change the era

**Comment by MelvinShwuaner** [comment]
you had an error where saved settings break when you try to load the file, i fixed it :]

**Comment by MelvinShwuaner** [comment]
you had an error where gods will keep getting their weapons even after already getting one, fixed :D

**Review by MasonScarbro — APPROVED** [review]

**Comment by MasonScarbro** [comment]
> you had an error where gods will keep getting their weapons even after already getting one, fixed :D, i am 99% sure that there is nothing left to do, so you can merge this if you want

I did BUT that is so they dont pick up any other weapons, despite how good the weapon they have is they will pick up something as stupid as a legendary stick, the way I had it made it so even if they pick it up they will be gifted the old weapon.

**Pull request merged**
