### PR TITLE
Morph ability

### PR DESCRIPTION
**Pull request by MelvinShwuaner**
this is a new ability that allows a god to change his asset, like a human turning into a dragon, while having the same name, age, traits, kingdom, minions

if a god morphs into a creature that cannot use items, then his city will take his items, if there is no city, the items will be lost

currently i havent made any gods use this ability yet, you can do that if you want

### CODE REVIEW

**Review by MasonScarbro — CHANGES_REQUESTED** [review]
```
public static void Inheritgodtraits(List<string> godtraits, ref ActorData God)
{
    foreach (string trait in godtraits)
    {
        if (Toolbox.randomChance(GetEnhancedChance(trait, trait+"inherit%", 55)))
        {
          if (!IsGodTrait(trait))
          {
                God.addTrait(trait);
          }
            God.addTrait("LesserGod");
        }
        else
        {
            God.addTrait("Failed God");
            God.set("Demi" + trait, true);
        }
    }
}
```

This is great stuff, I don't want to make a merge conflict So I figured I would just ask you to implement this change, So far I have tested this and haven't found any issues that have bothered me, but the current build seems to have the children of these gods inheriting the  actual god trait, I.e there can be two gods of light or darkness etc? (this causes conflicts when one dies) I replaced that with only lesser god which was the original plan for genealogy. That way they are either a lesser god or a demi god!

**Comment by MasonScarbro** [comment]
The mod draws inspiration from a variety of mythological and fantasy sources, including Greek mythology, the mythos of Lord of the Rings, and the divine pantheons of Elden Ring. The core idea is to feature a hierarchy of gods, from powerful major deities to lesser gods, each with their own unique powers and roles. Lesser gods, while formidable, will have powers that are more limited in scope compared to the major gods. In the future these powers may either be predefined by the user or procedurally generated to simulate divine traits. For example, in the context of Greek mythology, Dionysus—the son of Zeus—would be considered a lesser god despite his divine heritage. I mean power over wine is pretty cool but not exactly the strongest god to exist. 
Don't get me wrong I like the traits/stats they are given through inheritance I also just always had the vision of their children being lesser gods as their blood would be diluted as time goes on. Now with that being said I can see if the child kills their parent who is a major god they could inherit the title/powers of the major god.

**Comment by MelvinShwuaner** [comment]
hmmm, but if 2 gods have a child, then the child will be a god since the genes arent diluted? what if, if a god has a child with a mortal, it will be a demigod, which will inherit some of the stats of the god, if a god has a child with a demigod, then the child will be a lessergod, who will inherit the stats of the god along with some of his abilities, does that sound cool or is it dumb?

**Comment by MelvinShwuaner** [comment]
i have a cool idea, what if a god is always the leader of a clan, and everyone in his clan will be a lessergod, and:
god + god = lessergod who will inherit almost all of the stats and abilities of both of them
god + lessergod = lessergod but inherits more stuff
god + mortal = demigod
lessergod + demigod = failedgod
lessergod + mortal or lessergod + failedgod = demigod who inherits barely anything
failedgod + mortal = child who will inherit auto traits of god
failedgod + demigod = child who will inherit alot of the auto traits of god
failedgod + god = demigod

**Comment by MasonScarbro** [comment]
> i have a cool idea, what if a god is always the leader of a clan, and everyone in his clan will be a lessergod, and: god + god = lessergod who will inherit almost all of the stats and abilities of both of them god + lessergod = lessergod but inherits more stuff god + mortal = demigod if the child isnt in his clan god + demigod = demigod who inherits more lessergod + demigod = demigod who inherits a little lessergod + mortal = child who will inherit alot of the auto traits of god demigod + mortal = child who will inherit some of the auto traits of god
> 
> if a god dies, then its killer will become the new god

I agree!

**Comment by MelvinShwuaner** [comment]
hmmm, if a god is in a kingdom, should he always be the king?

**Comment by MelvinShwuaner** [comment]
Im done! here is what i have done:
-gods in a kingdom will always take higher priority when choosing kings (if multiple, the oldest will)
-summoned ones now have their own beh:
normally, summoned ones will be patrolling around their master, going from tile to tile, if a summoned one finds a enemy, he will other summoned ones and master (due to how the game works, the other summoned ones and master will only care if they are close by)
-if a master has an enemy, all nearby summoned ones will attack them
-summoned ones who dont have a master will get rid of the trait, if they have madness they will also get rid of it(differently)

-geneology: no more failed gods, there can only be one god, and there are lessergods and demigods

**Comment by MelvinShwuaner** [comment]
the last thing we have to do, is to let lessergods inherit abilities of gods (to make them much different then demigods) so dont merge this yet

**Review by MasonScarbro — APPROVED** [review]

**Comment by MasonScarbro** [comment]
> the last thing we have to do, is to let lessergods inherit abilities of gods (to make them much different then demigods) so dont merge this yet

Oops I didn't read this fully 😅

**Pull request merged**
